### PR TITLE
Fix MD5 comparision

### PR DESCRIPTION
**Pull request by mengjie0718**
add encrypt_md5

### CODE REVIEW

**Comment by houtianze** [comment]
Thanks very much for the PR.
I haven't really checked this repo for quite some time, what is this change about? Baidu made some breaking changes to the MD5 part?

**Comment by mengjie0718** [comment]
> Thanks very much for the PR.
> I haven't really checked this repo for quite some time, what is this change about? Baidu made some breaking changes to the MD5 part?

Yes,Baidu encrypted the MD5.

**Comment by houtianze** [comment]
Thanks. Let me verify later and merge once the change is confirmed to be
fine.

**Comment by houtianze** [comment]
Thanks, I can see the (encrypted) `MD5` values match.

Curious how did you figure out..

**Comment by houtianze** [comment]
Release `1.7.0` including this change is now live.

**Comment by landall** [comment]
> Thanks, I can see the (encrypted) `MD5` values match.
> 
> Curious how did you figure out..

Is the md5 still match now?

**Comment by Paper-Folding** [comment]
For small file, the encrypted md5 matches with Baidu Cloud API (response of `pan.baidu.com/api/list`); but for large file, it does not match. @mengjie0718 Do you know how to calculate encrypted md5 for large file? I want to verify local files with cloud ones? Thank you!

**Pull request merged**
