### PR TITLE
fix clerical error

### PR DESCRIPTION
**Pull request by krizex**
This is my first pull request on github.
I think this is a clerical error, is it?

### CODE REVIEW

**Comment by krizex** [comment]
Another issue:
When I want to upload a file to BaiduYun in back end, I use the command `nohup bypy.py upload xxx &` thus when I close the terminal, the task will still running. But when I close the terminal, and check the nohup log, the task is stopped when I disconnect from my VPS.
So I think we should not catch SIGHUP in the script.

**Comment by houtianze** [comment]
Thanks for the fixes. :smile: 

Yes, the first one is indeed a clerical error.

But I'm also surprised that my old code for the second one wasn't working under `nohup`, I _assumed_ that if run under `nohup`, it shouldn't receive any SIGHUP signal, but after I tried, it seems not the case. I think you are right that we should not change the SIGHUP handler.

**Comment by krizex** [comment]
I've checked source code of nohup, it set handler of SIGHUP  to SIG_IGN, then execv the command passed to it, so when this script catch the SIGHUP, it will reset handler of SIGHUP to the new one.

This is the backtrace of the scenario which catch the SIGHUP signal:
Token file: '/home/qy/.bypy/bypy.json'
Hash Cache file: '/home/qy/.bypy/bypy.pickle'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = None
sys.stdout.encoding = None
sys.stderr.encoding = None
----

Signal 1 received, Abort
  File "/usr/local/bin/bypy.py", line 3493, in <module>
    main()
  File "/usr/local/bin/bypy.py", line 3453, in main
    result = getattr(by, args.command[0])(*uargs)
  File "/usr/local/bin/bypy.py", line 2286, in upload
    return self.__upload_file(lpath, rpath, ondup)
  File "/usr/local/bin/bypy.py", line 2237, in __upload_file
    result = self.__upload_file_slices(localpath, remotepath, ondup)
  File "/usr/local/bin/bypy.py", line 2070, in __upload_file_slices
    ec = self.__upload_slice(remotepath)
  File "/usr/local/bin/bypy.py", line 2039, in __upload_slice
    files = { 'file' : ('file', self.__current_slice) } )
  File "/usr/local/bin/bypy.py", line 1445, in __post
    return self.__request(url, pars, act, 'POST', actargs, retry, addtoken, dumpex, **kwargs)
  File "/usr/local/bin/bypy.py", line 1421, in __request
    result = self.__request_work(url, pars, act, method, actargs, addtoken, dumpex, **kwnew)
  File "/usr/local/bin/bypy.py", line 1255, in __request_work
    params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 330, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 542, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 367, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 805, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/ssl.py", line 329, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python2.7/ssl.py", line 298, in send
    v = self._sslobj.write(data)
Stack:

**Comment by houtianze** [comment]
That's Fast & Cool :smile: Then I think that explains the behavior well.

**Pull request merged**
